version: '3.8'

services:
  mongo:
    image: mongo
    container_name: Test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  app:
    build: .
    container_name: code-base
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
